/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace cAudio {

using System;
using System.Runtime.InteropServices;

public class IAudioManager : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IAudioManager(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(IAudioManager obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IAudioManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cAudioCSharpWrapperPINVOKE.delete_IAudioManager(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual bool initialize(string deviceName, int outputFrequency, int eaxEffectSlots) {
    bool ret = cAudioCSharpWrapperPINVOKE.IAudioManager_initialize__SWIG_0(swigCPtr, deviceName, outputFrequency, eaxEffectSlots);
    return ret;
  }

  public virtual bool initialize(string deviceName, int outputFrequency) {
    bool ret = cAudioCSharpWrapperPINVOKE.IAudioManager_initialize__SWIG_1(swigCPtr, deviceName, outputFrequency);
    return ret;
  }

  public virtual bool initialize(string deviceName) {
    bool ret = cAudioCSharpWrapperPINVOKE.IAudioManager_initialize__SWIG_2(swigCPtr, deviceName);
    return ret;
  }

  public virtual bool initialize() {
    bool ret = cAudioCSharpWrapperPINVOKE.IAudioManager_initialize__SWIG_3(swigCPtr);
    return ret;
  }

  public virtual void shutDown() {
    cAudioCSharpWrapperPINVOKE.IAudioManager_shutDown(swigCPtr);
  }

  public virtual void update() {
    cAudioCSharpWrapperPINVOKE.IAudioManager_update(swigCPtr);
  }

  public virtual bool isUpdateThreadRunning() {
    bool ret = cAudioCSharpWrapperPINVOKE.IAudioManager_isUpdateThreadRunning(swigCPtr);
    return ret;
  }

  public virtual IAudioSource getSoundByName(string name) {
    IntPtr cPtr = cAudioCSharpWrapperPINVOKE.IAudioManager_getSoundByName(swigCPtr, name);
    IAudioSource ret = (cPtr == IntPtr.Zero) ? null : new IAudioSource(cPtr, false);
    return ret;
  }

  public virtual void releaseAllSources() {
    cAudioCSharpWrapperPINVOKE.IAudioManager_releaseAllSources(swigCPtr);
  }

  public virtual void release(IAudioSource source) {
    cAudioCSharpWrapperPINVOKE.IAudioManager_release(swigCPtr, IAudioSource.getCPtr(source));
  }

  public virtual string getAvailableDeviceName(uint index) {
    string ret = cAudioCSharpWrapperPINVOKE.IAudioManager_getAvailableDeviceName(swigCPtr, index);
    return ret;
  }

  public virtual uint getAvailableDeviceCount() {
    uint ret = cAudioCSharpWrapperPINVOKE.IAudioManager_getAvailableDeviceCount(swigCPtr);
    return ret;
  }

  public virtual string getDefaultDeviceName() {
    string ret = cAudioCSharpWrapperPINVOKE.IAudioManager_getDefaultDeviceName(swigCPtr);
    return ret;
  }

  public virtual IAudioSource create(string name, string filename, bool stream) {
    IntPtr cPtr = cAudioCSharpWrapperPINVOKE.IAudioManager_create__SWIG_0(swigCPtr, name, filename, stream);
    IAudioSource ret = (cPtr == IntPtr.Zero) ? null : new IAudioSource(cPtr, false);
    return ret;
  }

  public virtual IAudioSource create(string name, string filename) {
    IntPtr cPtr = cAudioCSharpWrapperPINVOKE.IAudioManager_create__SWIG_1(swigCPtr, name, filename);
    IAudioSource ret = (cPtr == IntPtr.Zero) ? null : new IAudioSource(cPtr, false);
    return ret;
  }

  public virtual IAudioSource createFromMemory(string name, string data, uint length, string extension) {
    IntPtr cPtr = cAudioCSharpWrapperPINVOKE.IAudioManager_createFromMemory(swigCPtr, name, data, length, extension);
    IAudioSource ret = (cPtr == IntPtr.Zero) ? null : new IAudioSource(cPtr, false);
    return ret;
  }

  public virtual IAudioSource createFromRaw(string name, string data, uint length, uint frequency, SWIGTYPE_p_AudioFormats format) {
    IntPtr cPtr = cAudioCSharpWrapperPINVOKE.IAudioManager_createFromRaw(swigCPtr, name, data, length, frequency, SWIGTYPE_p_AudioFormats.getCPtr(format));
    IAudioSource ret = (cPtr == IntPtr.Zero) ? null : new IAudioSource(cPtr, false);
    if (cAudioCSharpWrapperPINVOKE.SWIGPendingException.Pending) throw cAudioCSharpWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool registerAudioDecoder(IAudioDecoderFactory factory, string extension) {
    bool ret = cAudioCSharpWrapperPINVOKE.IAudioManager_registerAudioDecoder(swigCPtr, IAudioDecoderFactory.getCPtr(factory), extension);
    return ret;
  }

  public virtual void unRegisterAudioDecoder(string extension) {
    cAudioCSharpWrapperPINVOKE.IAudioManager_unRegisterAudioDecoder(swigCPtr, extension);
  }

  public virtual bool isAudioDecoderRegistered(string extension) {
    bool ret = cAudioCSharpWrapperPINVOKE.IAudioManager_isAudioDecoderRegistered(swigCPtr, extension);
    return ret;
  }

  public virtual IAudioDecoderFactory getAudioDecoderFactory(string extension) {
    IntPtr cPtr = cAudioCSharpWrapperPINVOKE.IAudioManager_getAudioDecoderFactory(swigCPtr, extension);
    IAudioDecoderFactory ret = (cPtr == IntPtr.Zero) ? null : new IAudioDecoderFactory(cPtr, false);
    return ret;
  }

  public virtual void unRegisterAllAudioDecoders() {
    cAudioCSharpWrapperPINVOKE.IAudioManager_unRegisterAllAudioDecoders(swigCPtr);
  }

  public virtual bool registerDataSource(SWIGTYPE_p_IDataSourceFactory factory, string name, int priority) {
    bool ret = cAudioCSharpWrapperPINVOKE.IAudioManager_registerDataSource(swigCPtr, SWIGTYPE_p_IDataSourceFactory.getCPtr(factory), name, priority);
    return ret;
  }

  public virtual void unRegisterDataSource(string name) {
    cAudioCSharpWrapperPINVOKE.IAudioManager_unRegisterDataSource(swigCPtr, name);
  }

  public virtual bool isDataSourceRegistered(string name) {
    bool ret = cAudioCSharpWrapperPINVOKE.IAudioManager_isDataSourceRegistered(swigCPtr, name);
    return ret;
  }

  public virtual SWIGTYPE_p_IDataSourceFactory getDataSourceFactory(string name) {
    IntPtr cPtr = cAudioCSharpWrapperPINVOKE.IAudioManager_getDataSourceFactory(swigCPtr, name);
    SWIGTYPE_p_IDataSourceFactory ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_IDataSourceFactory(cPtr, false);
    return ret;
  }

  public virtual void unRegisterAllDataSources() {
    cAudioCSharpWrapperPINVOKE.IAudioManager_unRegisterAllDataSources(swigCPtr);
  }

  public virtual void registerEventHandler(SWIGTYPE_p_IManagerEventHandler handler) {
    cAudioCSharpWrapperPINVOKE.IAudioManager_registerEventHandler(swigCPtr, SWIGTYPE_p_IManagerEventHandler.getCPtr(handler));
  }

  public virtual void unRegisterEventHandler(SWIGTYPE_p_IManagerEventHandler handler) {
    cAudioCSharpWrapperPINVOKE.IAudioManager_unRegisterEventHandler(swigCPtr, SWIGTYPE_p_IManagerEventHandler.getCPtr(handler));
  }

  public virtual void unRegisterAllEventHandlers() {
    cAudioCSharpWrapperPINVOKE.IAudioManager_unRegisterAllEventHandlers(swigCPtr);
  }

  public virtual SWIGTYPE_p_IListener getListener() {
    IntPtr cPtr = cAudioCSharpWrapperPINVOKE.IAudioManager_getListener(swigCPtr);
    SWIGTYPE_p_IListener ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_IListener(cPtr, false);
    return ret;
  }

}

}
